font_family      ProFontWindows Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 16.0

background #191919

# Previous tab
map alt+h previous_tab

# Next tab
map alt+l next_tab

map ctrl+shift+d launch --type=tab --cwd=current

color0   #262626   # darker, warmer gray (base)
color8   #aeb4bf   # muted light gray

color1   #dc322f   # solarized red (less harsh)
color9   #cb4b47   # softer bright red

color2   #859900   # olive green (solarized style)
color10  #93a61a   # brighter but still muted green

color3   #b58900   # mustard yellow
color11  #c59a1a   # softer bright yellow

color4   #268bd2   # solarized blue
color12  #3a94d6   # slightly brighter blue

color5   #6c71c4   # muted violet
color13  #7c80d4   # brighter violet

color6   #2aa198   # teal/cyan (less electric)
color14  #3bb2a9   # brighter cyan

color7   #c0c6cf   # light gray (not pure)
color15  #e6e8ef   # soft white (less harsh than #fff)

# BEGIN_KITTY_THEME
# Noctalia
# include ./themes/Brogrammer.conf
# END_KITTY_THEME
